export type WifiCategory = "cafe" | "restaurant" | "bar" | "hotel" | "library" | "gym" | "mall" | "other";
export type WifiSpeed = "slow" | "moderate" | "fast" | "ultra_fast";

export interface WifiSpot {
  id: string;
  name: string;
  address: string;
  ssid: string;
  password: string;
  category: WifiCategory;
  lat: number;
  lng: number;
  upvotes: number;
  downvotes: number;
  verified: boolean;
  speed: WifiSpeed;
  createdAt: string;
  isOutdated: boolean;
}

export const SEED_SPOTS: WifiSpot[] = [
  {
    id: "seed_1",
    name: "McDonald's Калуга",
    address: "ул. Кирова, 1, Калуга",
    ssid: "McDonalds Free WiFi",
    password: "",
    category: "restaurant",
    lat: 54.516,
    lng: 36.2573,
    upvotes: 14,
    downvotes: 1,
    verified: true,
    speed: "moderate",
    createdAt: "2025-11-15T10:00:00Z",
    isOutdated: false,
  },
  {
    id: "seed_2",
    name: "Кофейня «Кофе Хауз»",
    address: "пр-т Ленина, 73, Калуга",
    ssid: "KofeHaus_WiFi",
    password: "coffee2024",
    category: "cafe",
    lat: 54.5234,
    lng: 36.2614,
    upvotes: 22,
    downvotes: 2,
    verified: true,
    speed: "fast",
    createdAt: "2025-10-08T09:30:00Z",
    isOutdated: false,
  },
  {
    id: "seed_3",
    name: "Библиотека им. Белинского",
    address: "ул. Луначарского, 4, Калуга",
    ssid: "Library_Kaluga",
    password: "biblio123",
    category: "library",
    lat: 54.5312,
    lng: 36.2701,
    upvotes: 31,
    downvotes: 0,
    verified: true,
    speed: "fast",
    createdAt: "2025-09-20T14:00:00Z",
    isOutdated: false,
  },
  {
    id: "seed_4",
    name: "Ресторан «Пиноккио»",
    address: "ул. Театральная, 18, Калуга",
    ssid: "Pinoccio_Guest",
    password: "pinocchio",
    category: "restaurant",
    lat: 54.5198,
    lng: 36.2689,
    upvotes: 9,
    downvotes: 3,
    verified: false,
    speed: "moderate",
    createdAt: "2025-12-01T12:00:00Z",
    isOutdated: false,
  },
  {
    id: "seed_5",
    name: "KFC Калуга",
    address: "ул. Кирова, 12, Калуга",
    ssid: "KFC Free WiFi",
    password: "",
    category: "restaurant",
    lat: 54.5148,
    lng: 36.2601,
    upvotes: 18,
    downvotes: 1,
    verified: true,
    speed: "moderate",
    createdAt: "2025-08-14T11:00:00Z",
    isOutdated: false,
  },
  {
    id: "seed_6",
    name: "Отель «Калуга»",
    address: "ул. Кирова, 1Б, Калуга",
    ssid: "Hotel_Kaluga",
    password: "hotel2025",
    category: "hotel",
    lat: 54.5276,
    lng: 36.2643,
    upvotes: 7,
    downvotes: 2,
    verified: true,
    speed: "fast",
    createdAt: "2025-07-22T08:00:00Z",
    isOutdated: false,
  },
  {
    id: "seed_7",
    name: "ТЦ «Плаза»",
    address: "ул. Московская, 237, Калуга",
    ssid: "Plaza_WiFi",
    password: "plaza1234",
    category: "mall",
    lat: 54.5238,
    lng: 36.2788,
    upvotes: 25,
    downvotes: 5,
    verified: true,
    speed: "fast",
    createdAt: "2025-06-10T10:00:00Z",
    isOutdated: false,
  },
  {
    id: "seed_8",
    name: "Кафе «Уют»",
    address: "ул. Суворова, 7, Калуга",
    ssid: "Uyut_Free",
    password: "uyut2024",
    category: "cafe",
    lat: 54.5289,
    lng: 36.272,
    upvotes: 12,
    downvotes: 1,
    verified: true,
    speed: "moderate",
    createdAt: "2025-11-05T15:00:00Z",
    isOutdated: false,
  },
  {
    id: "seed_9",
    name: "Бар «Алиби»",
    address: "ул. Дзержинского, 34, Калуга",
    ssid: "Alibi_Bar",
    password: "alibi777",
    category: "bar",
    lat: 54.5217,
    lng: 36.2657,
    upvotes: 6,
    downvotes: 4,
    verified: false,
    speed: "slow",
    createdAt: "2025-10-18T20:00:00Z",
    isOutdated: false,
  },
  {
    id: "seed_10",
    name: "Кофейня «Бариста»",
    address: "пл. Старый Торг, 2, Калуга",
    ssid: "Barista_WiFi",
    password: "coffee123",
    category: "cafe",
    lat: 54.5157,
    lng: 36.2565,
    upvotes: 19,
    downvotes: 0,
    verified: true,
    speed: "ultra_fast",
    createdAt: "2025-09-01T09:00:00Z",
    isOutdated: false,
  },
  {
    id: "seed_11",
    name: "Областная научная библиотека",
    address: "ул. Ленина, 101, Калуга",
    ssid: "ONB_Kaluga",
    password: "library2024",
    category: "library",
    lat: 54.5304,
    lng: 36.269,
    upvotes: 28,
    downvotes: 1,
    verified: true,
    speed: "fast",
    createdAt: "2025-05-12T10:00:00Z",
    isOutdated: false,
  },
  {
    id: "seed_12",
    name: "Гипермаркет «Лента»",
    address: "ул. Азаровская, 11, Калуга",
    ssid: "Lenta_Free",
    password: "",
    category: "mall",
    lat: 54.5125,
    lng: 36.2528,
    upvotes: 11,
    downvotes: 2,
    verified: true,
    speed: "moderate",
    createdAt: "2025-04-30T11:00:00Z",
    isOutdated: false,
  },
  {
    id: "seed_13",
    name: "Пицца «Додо»",
    address: "ул. Московская, 178, Калуга",
    ssid: "Dodo_WiFi",
    password: "dodo2025",
    category: "restaurant",
    lat: 54.5245,
    lng: 36.2702,
    upvotes: 15,
    downvotes: 2,
    verified: true,
    speed: "fast",
    createdAt: "2025-03-20T12:00:00Z",
    isOutdated: false,
  },
  {
    id: "seed_14",
    name: "Отель «Центральный»",
    address: "пл. Победы, 1, Калуга",
    ssid: "Central_Hotel",
    password: "central99",
    category: "hotel",
    lat: 54.5265,
    lng: 36.2673,
    upvotes: 8,
    downvotes: 3,
    verified: false,
    speed: "moderate",
    createdAt: "2025-02-14T14:00:00Z",
    isOutdated: true,
  },
  {
    id: "seed_15",
    name: "Фитнес-клуб «Атлет»",
    address: "ул. Октябрьская, 45, Калуга",
    ssid: "Athlet_Gym",
    password: "fitness2024",
    category: "gym",
    lat: 54.5193,
    lng: 36.273,
    upvotes: 5,
    downvotes: 1,
    verified: false,
    speed: "fast",
    createdAt: "2025-01-08T08:00:00Z",
    isOutdated: false,
  },
];
